# .gitlab-ci.yml

# Install dependencies
before_script:
  - apt-get update -yqq
  - apt-get install -yqq nodejs npm php-cli
  

# JavaScript linting job
image: node:latest

stages:
  - lint

eslint:
  stage: lint
  script:
    # Install ESLint in this docker container
    - npm install -g eslint
    # Configure ESLint (will read your .eslintrc file)
    - eslint --init
    # Run ESLint
    - npm init @eslint/config
    - eslint **/*.js

# PHP linting job
