# .gitlab-ci.yml

# Install dependencies
before_script:
  - apt-get update -yqq
  - apt-get install -yqq nodejs npm php-cli
  - npm install -g eslint

# JavaScript linting job
js_lint:
  script:
    - eslint .
  only:
    - main

# PHP linting job
php_lint:
  script:
    - find . -name "*.php" -exec php -l {} \;
  only:
    - main
    - push