stages:
  - format
  - test

include:
  - template: Dependency-Scanning.gitlab-ci.yml

format:
  stage: format
  script: composer format

dependency_scanning:
  stage: test
  variables:
    CI_DEBUG_TRACE: 'true'
    DS_EXCLUDED_ANALYZERS: "bundler-audit, gemnasium-maven, gemnasium-python, retire.js"
  
