stages:
  - lint

php-lint:
  stage: lint
  image: php:latest
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq git zip unzip
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer global require jakub-onderka/php-parallel-lint
    - export PATH="$PATH:/root/.composer/vendor/bin"
  script:
    - parallel-lint --exclude vendor --no-colors .