stages:
  - qa

include:
  - template: Dependency-Scanning.gitlab-ci.yml

dependency_scanning:
  stage: qa
  variables:
    CI_DEBUG_TRACE: 'true'
    DS_EXCLUDED_ANALYZERS: "bundler-audit, gemnasium-maven, gemnasium-python, retire.js"
  
