# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
before_script:
- DEBIAN_FRONTEND=noninteractive apt-get update -yqq
- DEBIAN_FRONTEND=noninteractive apt-get install -yqq php-cli
- DEBIAN_FRONTEND=noninteractive
lint:
  script:
  - find . -name "*.php" -exec php -l {} \;
include:
- template: Security/Dependency-Scanning.gitlab-ci.yml
