image: node



# Lets name our Job eslint, because that's what it's doing.
eslint:

 # What scripts do we want to run?
 script:
    # install eslint
    - npm i eslint
    # Run eslint
    - node_modules/eslint/bin/eslint.js .