image: node

stages:
  - lint

eslint:
  stage: lint
  script:
    # Install eslint
    - |
      npm install eslint \
      eslint-config-airbnb \
      eslint-config-prettier \
      eslint-plugin-flowtype
    # Run eslint
    - npm init @eslint/config
    - node_modules/eslint/bin/eslint.js .