<?php
    session_start();

    use PHPMailer\PHPMailer\PHPMailer;
    use PHPMailer\PHPMailer\Exception;

    require_once '../../vendor/composer/src/Exception.php';
    require_once '../../vendor/composer/src/PHPMailer.php';
    require_once '../../vendor/composer/src/SMTP.php';
    require_once '../../vendor/autoload.php';

    require_once "../includes/functions/getEmailGroups.php";
    include_once "../includes/functions/security.php";
    DefineSecurity();
    include_once "../db/database.php";
    include_once "../db/dbFunctions.php";

    // Prevent direct access and prevent non-admin's to access
    RestrictAdmin(CheckRole($_SESSION['User_ID']));
    defined('_DEFVAR') or exit(header('Location: ../index.php'));


    // Checking if form button was pressed
    if ($_SERVER["REQUEST_METHOD"] == "POST") { // Processing email
        // Reading email inputs
        $emailSubject = sanitizeData($_REQUEST['emailFormTitle']);
        $emailName = sanitizeData($_REQUEST['emailFormFullName']);
        $emailBody = $_REQUEST['emailFormTextBox'];
        $emailRecipientsJSON = json_decode($_REQUEST['email-recipient-json']); // Note: No sanitization needed because generated by JS






        // Obtaining emailing list from JSON object
        $emailList = getEmailList($emailRecipientsJSON);







        // Configuring email
        $mail = new PHPMailer(true);
        $mail->isSMTP(); // Remove line to view debug output
        $mail->Mailer = 'smtp';
        $mail->SMTPDebug = 0;
        $mail->SMTPAuth = TRUE;
        $mail->SMTPSecure = "tls";
        $mail->Port = 26;
        $mail->Host = "mail.cricketnovascotia.ca";
        $mail->Username = "testadmin@cricketnovascotia.ca";
        $mail->Password = "CricketNSCA";
        $mail->isHTML(true);

        // Assigning subject
        $mail->Subject = $emailSubject;

        // Assigning From name
        if ($emailName != "") {
            try {
                $mail->SetFrom("testadmin@cricketnovascotia.ca", $emailName);
            } catch (Exception $e) {
                header("Location: sendEmail.php?error");  // Error: Email processing exception
            }
        } else {
            try {
                $mail->SetFrom("testadmin@cricketnovascotia.ca", "Test Admin");
            } catch (Exception $e) {
                header("Location: sendEmail.php?error");  // Error: Email processing exception
            }
        }

        // Adding emails to BCC
        foreach ($emailList as $email) {
            try {
                $mail->addBcc($email, "toAddress");
            } catch (Exception $e) {
                echo "<script> console.log('Error adding " . $email . " email to BCC.') </script>";
            }
        }

        // Assigning body
        $mail->Body = $emailBody;
        try {
            $mail->MsgHTML($emailBody);
        } catch (Exception $e) {
            header("Location: sendEmail.php?error"); // Error: Email processing exception
        }

        // Sending email
        try {
            if ($mail->Send()) {
                var_dump($mail);
                header("Location: sendEmail.php?success"); // Success: Email sent
            } else {
                var_dump($mail);
                header("Location: sendEmail.php?error"); // Error: Email sending error
            }
        } catch (Exception $e) {
            header("Location: sendEmail.php?error"); // Error: Email sending error
        }
    }
    else {
        header("Location: sendEmail.php?error"); // Error: Form not submitted
    }


    // Functions
    function getEmailList($emailRecipientsJSON) {
        $emailList = array();

        // Adding individual emails to list
        foreach ($emailRecipientsJSON->individualEmails as $email) {
            array_push($emailList, $email);
        }

        // Adding each group to the list
        foreach($emailRecipientsJSON->emailGroups as $emailGroup) {
            $substring = strtok($emailGroup, "_"); // Tokenize string

            // Finding type of group
            switch ($substring) {
                case "all":
                    $substring = strtok("_"); // Next substring

                    // Adding specific 'All' group
                    switch ($substring) {
                        case "users":
                            array_push($emailList, getAllUserEmails());
                            break;

                        case "clubs":
                            array_push($emailList, getAllClubTeamUserEmails());
                            break;

                        case "programs":
                            array_push($emailList, getAllProgramUserEmails());
                            break;
                    }

                    break;

                case "club":
                    break;

                case "team":
                    break;

                case "region":
                    break;

                case "program":
                    break;

                case "committee":
                    break;
            }



            // Removing duplicate emails
            $emailList = array_unique($emailList);
        }

        return $emailList;
    }

?>

<head>
    <meta charset="utf-8">
    <title>Sending Email...</title>
    <link rel="icon" href="../img/favicon.jpeg">
</head>
